#!/bin/bash
sudo -s

# Sync Time
ntpdate ntp.ubuntu.com

# Fix locale
locale-gen en_US.UTF-8
export LANG=en_US.UTF-8

# Update packages
apt-get update && apt-get upgrade

# Install latest stable Nginx
apt-get install python-software-properties software-properties-common
add-apt-repository ppa:nginx/stable
apt-get update
apt-get install nginx-extras
 
# Install MySQL 5.6
apt-get install mysql-server-5.6 mysql-client-5.6
 
# Install PHP 5.6
add-apt-repository ppa:ondrej/php5-5.6
apt-get install php5-common php5-fpm php5-dev php5-mysql php5-curl php5-geoip php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl php5-apcu
 
sudo nginx -s reload
